//! List of migrations for the current app.
//!
//! Generated by cot CLI 0.2.0 on 2025-04-01 00:10:41+00:00

pub mod m_0001_initial;
/// The list of migrations for current app.
pub const MIGRATIONS: &[&::cot::db::migrations::SyncDynMigration] = &[&m_0001_initial::Migration];
