//! Generated by cot CLI 0.1.0 on 2024-08-28 13:39:05+00:00

#[derive(Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "example-todo-list";
    const MIGRATION_NAME: &'static str = "m_0001_initial";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] =
        &[::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("todo_item"))
            .fields(&[
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("id"),
                    <i32 as ::cot::db::DatabaseField>::TYPE,
                )
                .auto()
                .primary_key(),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("title"),
                    <String as ::cot::db::DatabaseField>::TYPE,
                ),
            ])
            .build()];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _TodoItem {
    #[model(primary_key)]
    id: i32,
    title: String,
}
