//! Generated by flareon CLI 0.1.0 on 2024-08-21 13:34:43+00:00

pub(super) struct Migration;
impl ::flareon::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "example-todo-list";
    const MIGRATION_NAME: &'static str = "m_0001_initial";
    const OPERATIONS: &'static [::flareon::db::migrations::Operation] =
        &[::flareon::db::migrations::Operation::CreateModel {
            table_name: ::flareon::db::Identifier::new("todo_item"),
            fields: &[
                ::flareon::db::migrations::Field::new(
                    ::flareon::db::Identifier::new("id"),
                    <i32 as ::flareon::db::DbField>::TYPE,
                )
                .primary_key()
                .auto(),
                ::flareon::db::migrations::Field::new(
                    ::flareon::db::Identifier::new("title"),
                    <String as ::flareon::db::DbField>::TYPE,
                ),
            ],
        }];
}

#[derive(::core::fmt::Debug)]
#[::flareon::db::model(model_type = "migration")]
struct _TodoItem {
    id: i32,
    title: String,
}
