//! Generated by cot CLI 0.3.1 on 2025-06-19 20:48:22+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "forms";
    const MIGRATION_NAME: &'static str = "m_0001_initial";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] =
        &[::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("forms__example_form_item"))
            .fields(&[
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("id"),
                    <cot::db::Auto<i32> as ::cot::db::DatabaseField>::TYPE,
                )
                .auto()
                .primary_key()
                .set_null(<cot::db::Auto<i32> as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("title"),
                    <String as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("datetime"),
                    <chrono::NaiveDateTime as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<chrono::NaiveDateTime as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("datetime_tz"),
                    <chrono::DateTime<chrono::FixedOffset> as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(
                    <chrono::DateTime<chrono::FixedOffset> as ::cot::db::DatabaseField>::NULLABLE,
                ),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("time"),
                    <chrono::NaiveTime as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<chrono::NaiveTime as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("date"),
                    <chrono::NaiveDate as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<chrono::NaiveDate as ::cot::db::DatabaseField>::NULLABLE),
            ])
            .build()];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _ExampleFormItem {
    #[model(primary_key)]
    id: cot::db::Auto<i32>,
    title: String,
    datetime: chrono::NaiveDateTime,
    datetime_tz: chrono::DateTime<chrono::FixedOffset>,
    time: chrono::NaiveTime,
    date: chrono::NaiveDate,
}
